# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./Api/Api.csproj .
RUN dotnet restore

# Copy everything else and build
COPY ./Api .
RUN dotnet build

# Build runtime image
FROM mcr.microsoft.com/dotnet/sdk:8.0
ENV ASPNETCORE_HTTP_PORTS=80
WORKDIR /app
RUN dotnet dev-certs https
COPY --from=build-env /app .
