# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./Api/Api.csproj .
RUN dotnet restore

# Copy everything else and build
COPY ./Api .
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /usr/src/dotnet
RUN dotnet dev-certs https
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "Api.dll"]