version: "3.8"

services:
  nextjs:
    container_name: nextjs_app
    build: ./nextjs
    ports:
      - 3000:3000
    env_file:
      - ./nextjs/.env
  flaskapp:
    build: ./flaskapp
    container_name: flask_app
    command: python app.py
    volumes:
      - flaskapp:/usr/src/app/
    expose:
      - 8080
    ports:
      - 5001:5001
    env_file:
      - ./flaskapp/build/.env
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:13-alpine
    volumes:
      - ppjkdb:/var/lib/postgresql/data/
    env_file:
      - ./flaskapp/db/.env
    ports:
      - "5432:5432"

volumes:
  ppjkdb:
  flaskapp:
