version: "3.8"

services:
  nextjs:
    container_name: nextjs_app
    build: ./nextjs
    restart: always
    expose:
      - 3000
    env_file:
      - ./nextjs/.env.prod

  # flaskapp:
  #   build:
  #     context: ./flaskapp
  #     dockerfile: dockerfile.prod
  #   container_name: flask_api
  #   command: gunicorn --bind 0.0.0.0:5000 wsgi:my_app
  #   expose:
  #     - 5000
  #   env_file:
  #     - ./flaskapp/build/.env.prod

  dotnet:
    build:
      context: ./cs
      dockerfile: dockerfile.prod
    container_name: dotnet_api
    expose:
      - 5002
    depends_on:
      - mongodb

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - ./logs/nginx:/var/log/nginx:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dotnet

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  redis:
    container_name: redis_cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
