version: "3.8"

services:
  nextjs:
    container_name: nextjs_app
    build: ./nextjs
    ports:
      - 3001:3001
    env_file:
      - ./nextjs/.env.local
  flaskapp:
    build: ./flaskapp
    container_name: flask_app
    command: python app.py
    volumes:
      - ./flaskapp/build:/usr/src/app/
    expose:
      - 8080
    ports:
      - 5001:5001
    env_file:
      - ./flaskapp/build/.env

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db/

  dotnet:
    build:
      context: ./cs
      dockerfile: dockerfile
    container_name: dotnet_api
    command: dotnet watch
    volumes:
      - ./cs/Api/src:/usr/src/app/
    ports:
      - 5002:5002
    env_file:
      - ./cs/Api/.env
    depends_on:
      - mongodb

  redis:
    container_name: redis_cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis:/data

volumes:
  mongodb:
