// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace myapi.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220227215135_firstmigration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("character varying(100000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("02774989-0e37-4a21-9d96-d239dbb3820f"),
                            Content = "content 0",
                            CreatedOn = new DateTime(2022, 2, 27, 21, 51, 34, 881, DateTimeKind.Utc).AddTicks(150),
                            Title = "post 0"
                        },
                        new
                        {
                            PostId = new Guid("b85a0821-b0d9-478c-8cad-27dc9291ad9f"),
                            Content = "content 1",
                            CreatedOn = new DateTime(2022, 2, 27, 21, 51, 34, 881, DateTimeKind.Utc).AddTicks(200),
                            Title = "post 1"
                        },
                        new
                        {
                            PostId = new Guid("87af72af-1f1b-4ba1-848f-b8b154add88d"),
                            Content = "content 2",
                            CreatedOn = new DateTime(2022, 2, 27, 21, 51, 34, 881, DateTimeKind.Utc).AddTicks(250),
                            Title = "post 2"
                        });
                });

            modelBuilder.Entity("PostRelation", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("PostId");

                    b.ToTable("PostRelations");

                    b.HasData(
                        new
                        {
                            PostId = new Guid("1437d980-79e9-40ab-b25a-680cad04e174"),
                            ChildId = new Guid("b85a0821-b0d9-478c-8cad-27dc9291ad9f"),
                            ParentId = new Guid("02774989-0e37-4a21-9d96-d239dbb3820f")
                        },
                        new
                        {
                            PostId = new Guid("a3b8bb70-de38-4727-a394-ff6dd9583d01"),
                            ChildId = new Guid("87af72af-1f1b-4ba1-848f-b8b154add88d"),
                            ParentId = new Guid("02774989-0e37-4a21-9d96-d239dbb3820f")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
