export const actions = {
  SET_SCROLLED: "SET_SCROLLED",
  SET_FOCUS: "SET_FOCUS",
  SET_LOGGED_IN: "SET_LOGGED_IN",
  SET_ACTIVE: "SET_ACTIVE",
  ADDING_BLOG_POST: "ADDING_BLOG_POST",
  IS_EDITING: "IS_EDITING",
  SET_WARNING: "SET_WARNING",
  SET_TITLE: "SET_TITLE",
  POSTING_MESSAGE: "POSTING_MESSAGE",
  SET_LOADER: "SET_LOADER",
  DELETE_POST: "DELETE_POST",
  IS_DELETING: "IS_DELETING",
  SELECT_PROJECT: "SELECT_PROJECT",
  SET_THEME: "SET_THEME",
};

export const blogActions = {
  SET_POSTS: "SET_POSTS",
  UPDATING_BLOG_POST: "UPDATING_BLOG_POST",
  SET_ACTIVE_POST: "SET_ACTIVE_POST",
  SET_DRAFT: "SET_DRAFT",
};
